import type { PropsWithChildren } from 'react'
import type { Metadata } from 'next'

import '@web/css/global.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
